### ISSUE TITLE
Tmisc depends on Biobase

### ISSUE THREAD

**Issue by safferli** [stephenturner/Tmisc#1]
Hi Stephen, thanks for your nice quick package to pull Anscombe's quartet. In trying to install the package I got an error that I needed Biobase. Some quick googleing showed me that I could not install that via the normal install.packages() way, but rather like this: 

source("http://bioconductor.org/biocLite.R")
biocLite("Biobase")

http://www.bioconductor.org/packages/release/bioc/html/Biobase.html

Just if someone has the same problem, I thought I'd bring this up here. After Biobase was installed everything worked great. Perhaps you can adjust the package dependencies accordingly?

**Comment by stephenturner** [comment]
Thanks. I wrote this package mostly for my own use, and I use the `exprs()` function from Biobase in one of my functions. I updated the README to reflect this dependency and to give instructions for installing Biobase.
